plt.plot(s, F2topsis,"k-d", label='Topsis')
plt.plot(s, F2knn_V1, 'm-s', label='KNN V1')
plt.plot(s, F2knn_V2, 'b-o', label='KNN V2')
plt.plot(s, F2knn_V3, 'y-*', label='KNN V3')
plt.suptitle('$F measure$')
#plt.set_title('F2')
plt.xlabel('$s$')
plt.ylabel('$F measure$')
plt.xlim(0.55,1)
plt.legend()